name: ci

on:
  push:
    paths:
      - '.github/workflows/ci.yml'
      - 'AliceOnboardingSampleApp/app/build.gradle'
    branches:
      - 'main'
  workflow_dispatch:
  
env:
  ALICE_GITHUB_ACCESS_TOKEN: ${{ secrets.ALICE_GITHUB_ACCESS_TOKEN }}
  GITHUB_API_URI: "https://api.github.com"
  GITHUB_API_HEADER: "Accept: application/vnd.github.v3+json"

jobs:
  connected-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [30]
        target: [google_apis]
        arch: [x86_64]
        
    steps:
      - name: checkout
        uses: actions/checkout@v4
        
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'adopt'
          cache: 'gradle'
        
      
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
        
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          working-directory: ./AliceOnboardingSampleApp
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: ${{ matrix.arch }}
          script: ./gradlew test connectedCheck
