name: ci

on:
  release:
    types: # This configuration does not affect the page_build event above
      - created
  push:
    paths:
      - '.github/workflows/ci.yml'
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Tests [UI test]
      uses: vgaidarji/android-github-actions-emulator@v1.0.1
