name: ci

on:
  push:
    paths:
      - '.github/workflows/ci.yml'
      - 'AliceOnboardingSampleApp/app/build.gradle'
    branches:
      - 'main'
  workflow_dispatch:
  
env:
  ALICE_GITHUB_ACCESS_TOKEN: ${{ secrets.ALICE_GITHUB_ACCESS_TOKEN }}
  GITHUB_API_URI: "https://api.github.com"
  GITHUB_API_HEADER: "Accept: application/vnd.github.v3+json"
  
jobs:
  ci:
    runs-on: macOS-11
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          working-directory: ./AliceOnboardingSampleApp
          api-level: 29
          script: ./gradlew connectedCheck
          
