name: ci

on:
  release:
    types: # This configuration does not affect the page_build event above
      - created
  push:
    paths:
      - '.github/workflows/ci.yml'
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: actions/checkout@v1
    - name: Tests [UI test]
      working-directory: AppOnboardingSample/
      run: |
          ./gradlew connectedAndroidTest
