name: ci

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          working-directory: ./AliceOnboardingSampleApp
          api-level: 29
          script: ./gradlew connectedCheck


