name: ci

on:
  release:
    types: # This configuration does not affect the page_build event above
      - created
  push:
    paths:
      - '.github/workflows/ci.yml'
    branches:
      - 'master'

jobs:
  test:
    runs-on: macOS-10.15
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          working-directory: ./AliceOnboardingSampleApp
          api-level: 29
          script: ./gradlew connectedCheck


