name: ci

on:
  release:
    types: # This configuration does not affect the page_build event above
      - created
  push:
    paths:
      - '.github/workflows/ci.yml'
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.3

    - name: Set up our JDK environment
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8
        
    - name: Build all artifacts
      id: buildAllApks
      uses: eskatos/gradle-command-action@v1.3.3
      with:
        build-root-directory: AppOnboardingSample
        gradle-version: current
        wrapper-cache-enabled: true
        dependencies-cache-enabled: true
        configuration-cache-enabled: true
        arguments: assembleRelease
        
    - name: Run Unit Tests
      working-directory: AppOnboardingSample/
      run: |
          ./gradlew testStagingDebugUnitTest
