name: ci

on:
  push:
    paths:
      - '.github/workflows/ci.yml'
      - 'AliceOnboardingSampleApp/app/build.gradle'
    branches:
      - 'main'
  workflow_dispatch:
  
env:
  ALICE_GITHUB_ACCESS_TOKEN: ${{ secrets.ALICE_GITHUB_ACCESS_TOKEN }}
  GITHUB_API_URI: "https://api.github.com"
  GITHUB_API_HEADER: "Accept: application/vnd.github.v3+json"

jobs:
  connected-tests:
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
          cache: 'gradle'
        
      - name: Run connected tests
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          working-directory: ./AliceOnboardingSampleApp
          api-level: 30
          target: google_apis
          arch: x86_64
          script: ./gradlew connectedCheck
          
