name: ci

on:
  release:
    types: # This configuration does not affect the page_build event above
      - created
  push:
    paths:
      - '.github/workflows/ci.yml'
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.3

    - name: Set up our JDK environment
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8
        
    - name: Run Instrumented Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        working-directory: ./AppOnboardingSample
        api-level: 23
        target: default
        arch: x86
        profile: Nexus 6
        script: ./gradlew connectedAndroidTest --stacktrace
